name: CI

on:
  push:
    branches: main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  check:
    name: Continuous integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Check formatting
        run: deno fmt --check
