name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "styles/**/rose-pine.user.less"
      - "scripts/generate-imports"

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build import lists
        run: ./scripts/generate-imports

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload userstyle-imports rose-pine*-import.json --clobber
